---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-litts-xyz
  namespace: default
spec:
  secretName: local-litts-xyz-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.litts.xyz"
  dnsNames:
  - "*.litts.xyz"
